# Generated by Django 3.0.7 on 2020-06-17 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Batch_No', models.IntegerField()),
                ('collection_date', models.DateField(default=datetime.datetime.now)),
                ('pasteurizing_date', models.DateField(default=datetime.datetime.now)),
                ('batch_type', models.CharField(choices=[('Hetrogeneous', 'Hetrogeneous'), ('Homogeneous', 'Homogeneous')], max_length=20)),
                ('doner_id_homo', models.BooleanField()),
                ('self_other', models.BooleanField()),
                ('exp_date', models.DateField(default=datetime.datetime.now)),
                ('Pasturing_process_id', models.CharField(max_length=10)),
                ('content1', models.CharField(max_length=125)),
            ],
        ),
    ]
