# Generated by Django 3.0.7 on 2020-06-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lactoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='Batch_No',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='doner_id_homo',
            field=models.BooleanField(default=True),
        ),
    ]
