# Generated by Django 3.0.7 on 2020-06-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lactoApp', '0002_auto_20200617_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='Batch_No',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='batch',
            name='doner_id_homo',
            field=models.BooleanField(),
        ),
    ]
