# Generated by Django 3.0.7 on 2020-06-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lactoApp', '0003_auto_20200617_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='self_other',
            field=models.CharField(max_length=20),
        ),
    ]
