# Generated by Django 3.0.7 on 2020-06-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lactoApp', '0004_auto_20200617_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='select_type',
            field=models.CharField(default=-20, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_type',
            field=models.CharField(max_length=20),
        ),
    ]
