# Generated by Django 3.0.7 on 2020-06-17 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lactoApp', '0006_auto_20200617_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='test1_date',
        ),
    ]
