# Generated by Django 3.0.7 on 2020-06-17 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lactoApp', '0007_remove_batch_test1_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='test_id',
        ),
    ]
