# Generated by Django 3.0.7 on 2020-06-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lactoApp', '0008_remove_batch_test_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='select_type',
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_type',
            field=models.CharField(choices=[('Hetrogeneous', 'Hetrogeneous'), ('Homogeneous', 'Homogeneous')], max_length=20),
        ),
    ]
