# Generated by Django 3.0.7 on 2020-06-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lactoApp', '0010_auto_20200617_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_type',
            field=models.CharField(choices=[('Hetrogeneous', 'Hetrogeneous'), ('Homogeneous', 'Homogeneous')], max_length=20),
        ),
        migrations.AlterField(
            model_name='batch',
            name='self_other',
            field=models.CharField(max_length=20),
        ),
    ]
