# Generated by Django 3.0.7 on 2020-06-17 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lactoApp', '0012_auto_20200617_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('HBS_test_date', models.DateField(default=datetime.datetime.now)),
                ('HIV_test_date', models.DateField(default=datetime.datetime.now)),
                ('screening_test_date', models.DateField(default=datetime.datetime.now)),
                ('VRDL_test', models.BooleanField()),
                ('VRDL_test_date', models.DateField(default=datetime.datetime.now)),
                ('last_child_birth_date', models.DateField(default=datetime.datetime.now)),
                ('consent', models.BooleanField()),
                ('consent_date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
