# Generated by Django 3.0.7 on 2020-06-18 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lactoApp', '0013_doner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doner',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='Pasturing_process_id',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='batch_type',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='content1',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='doner_id_homo',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='exp_date',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='select_type',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='self_other',
        ),
    ]
