# Generated by Django 3.0.7 on 2020-06-18 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lactoApp', '0014_auto_20200618_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='collection_date',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='pasteurizing_date',
        ),
    ]
