# Generated by Django 3.0.7 on 2020-06-18 03:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lactoApp', '0015_auto_20200618_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='collection_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Collection Date'),
        ),
    ]
