# Generated by Django 3.0.7 on 2020-06-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lactoApp', '0017_auto_20200618_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='collection_date',
            field=models.DateField(),
        ),
    ]
