# Generated by Django 3.0.7 on 2020-06-18 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lactoApp', '0018_auto_20200618_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='pasteurizing_date',
        ),
        migrations.AlterField(
            model_name='batch',
            name='collection_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='batch',
            name='exp_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='doner',
            name='HBS_test_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='doner',
            name='HIV_test_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='doner',
            name='VRDL_test_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='doner',
            name='consent_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='doner',
            name='last_child_birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='doner',
            name='screening_test_date',
            field=models.DateField(),
        ),
    ]
