# Generated by Django 3.0.7 on 2020-06-18 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lactoApp', '0019_auto_20200618_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='Pasturing_process_id',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='batch',
            name='collection_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='batch',
            name='content1',
            field=models.CharField(blank=True, max_length=125),
        ),
        migrations.AlterField(
            model_name='batch',
            name='select_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='batch',
            name='self_other',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='doner',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='doner',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='doner',
            name='f_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='doner',
            name='l_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
