# Generated by Django 3.0.7 on 2020-06-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lactoApp', '0020_auto_20200618_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='doner',
            name='doner_id',
            field=models.CharField(default=11, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batch',
            name='doner_id_homo',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='exp_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='doner',
            name='HBS_test_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='doner',
            name='HIV_test_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='doner',
            name='VRDL_test',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='doner',
            name='VRDL_test_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='doner',
            name='consent',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='doner',
            name='consent_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='doner',
            name='last_child_birth_date',
            field=models.DateField(blank=True),
        ),
    ]
