# Generated by Django 3.0.7 on 2020-06-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lactoApp', '0021_auto_20200618_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doner',
            name='HBS_test_date',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='doner',
            name='HIV_test_date',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='doner',
            name='VRDL_test',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='doner',
            name='VRDL_test_date',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='doner',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='doner',
            name='age',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='doner',
            name='consent',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='doner',
            name='consent_date',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='doner',
            name='f_name',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='doner',
            name='l_name',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='doner',
            name='last_child_birth_date',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='doner',
            name='screening_test_date',
            field=models.DateField(default=None),
        ),
    ]
