# Generated by Django 3.0.7 on 2020-06-18 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lactoApp', '0024_auto_20200618_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doner',
            name='HBS_test_date',
        ),
        migrations.RemoveField(
            model_name='doner',
            name='HIV_test_date',
        ),
        migrations.RemoveField(
            model_name='doner',
            name='VRDL_test',
        ),
        migrations.RemoveField(
            model_name='doner',
            name='VRDL_test_date',
        ),
        migrations.RemoveField(
            model_name='doner',
            name='address',
        ),
        migrations.RemoveField(
            model_name='doner',
            name='age',
        ),
        migrations.RemoveField(
            model_name='doner',
            name='consent',
        ),
        migrations.RemoveField(
            model_name='doner',
            name='consent_date',
        ),
        migrations.RemoveField(
            model_name='doner',
            name='l_name',
        ),
        migrations.RemoveField(
            model_name='doner',
            name='last_child_birth_date',
        ),
        migrations.RemoveField(
            model_name='doner',
            name='screening_test_date',
        ),
    ]
