# Generated by Django 3.0.7 on 2020-06-18 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lactoApp', '0027_doner_l_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doner',
        ),
    ]
