# Generated by Django 3.0.7 on 2020-06-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lactoApp', '0028_delete_doner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doner_id', models.CharField(max_length=10)),
                ('f_name', models.CharField(blank=True, max_length=20)),
                ('l_name', models.CharField(blank=True, default=False, max_length=20)),
            ],
        ),
    ]
