# Generated by Django 3.0.7 on 2020-06-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lactoApp', '0029_doner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doner',
            name='l_name',
            field=models.CharField(blank=True, default=True, max_length=20),
        ),
    ]
