# Generated by Django 3.0.7 on 2020-06-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lactoApp', '0030_auto_20200618_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doner',
            name='l_name',
            field=models.CharField(blank='True', default=True, max_length=20),
        ),
    ]
