# Generated by Django 3.0.7 on 2020-06-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lactoApp', '0031_auto_20200618_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doner',
            name='f_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='doner',
            name='l_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
