# Generated by Django 3.0.7 on 2020-06-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lactoApp', '0032_auto_20200618_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='doner',
            name='HBS_test_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doner',
            name='HIV_test_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doner',
            name='VRDL_test',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doner',
            name='VRDL_test_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doner',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doner',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doner',
            name='consent',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='doner',
            name='consent_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='doner',
            name='last_child_birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='doner',
            name='screening_test_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
