# Generated by Django 3.0.7 on 2020-06-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lactoApp', '0033_auto_20200618_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='pasteurizing_date',
            field=models.DateField(null=True),
        ),
    ]
